# Generated by Django 2.0.2 on 2018-02-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewsfeed', '0006_guardianpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianpost',
            old_name='trail_text',
            new_name='trailText',
        ),
    ]
